### ISSUE TITLE
Cannot get this working

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/jupyter-panel-proxy#19]
I simply cannot get this working. 

- On windows it does not work because jupyter-server-proxy does not work.
- In docker container I cannot get this working
- On binder I cannot get this working.

I've realized its probably because the README has been updated without the package being released.

![image](https://user-images.githubusercontent.com/42288570/127749949-06c5e57e-80d4-41a9-9834-1b50836134f3.png)

**Comment by MarcSkovMadsen** [comment]
If I install 0.2.0a2 I seem to get something working. But I get the error below in the console

![image](https://user-images.githubusercontent.com/42288570/127750147-d9d6411a-bdfc-4d22-b9c6-cd11c08464e6.png)
![image](https://user-images.githubusercontent.com/42288570/127750065-6c6f2f82-4409-41e1-80f2-627a9b8600b0.png)

```bash
[E 2021-07-31 19:04:46.397 ServerApp] Uncaught exception GET /server-proxy/icon/panel (172.17.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8889', method='GET', uri='/server-proxy/icon/panel', version='HTTP/1.1', remote_ip='172.17.0.1')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/usr/local/lib/python3.7/site-packages/jupyter_server_proxy/api.py", line 68, in get
        with open(self.icons[name]) as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/site-packages/panel_server/icons/logo.svg'
```

My setup is here https://github.com/MarcSkovMadsen/awesome-panel-introduction/blob/144631113e539cbd6c63ac7e5c68b079456528c1/jupyter-panel-proxy.yml. I'm running it from this Docker image https://github.com/MarcSkovMadsen/awesome-panel-introduction/blob/144631113e539cbd6c63ac7e5c68b079456528c1/Dockerfile.jupyter

**Comment by MarcSkovMadsen** [comment]
Now I moved to binder and I managed to get something working.

Check out https://mybinder.org/v2/gh/marcskovmadsen/awesome-panel-introduction/main?urlpath=panel/introduction

![image](https://user-images.githubusercontent.com/42288570/127750940-3c42bb44-9a25-43d7-b94f-2c6e4fc691d7.png)

**Comment by MarcSkovMadsen** [comment]
If you open jupyter lab you https://mybinder.org/v2/gh/marcskovmadsen/awesome-panel-introduction/main?urlpath=lab/tree/presentation you will see the missing logo

![image](https://user-images.githubusercontent.com/42288570/127750977-1b42f8ae-1d3c-4f75-82df-333c4c5339e7.png)

But when I click the button it still works as expected and looks nice

![image](https://user-images.githubusercontent.com/42288570/127750988-ad4e6ac0-f48b-451c-af81-b67bc06c6b88.png)

**Comment by maximlt** [comment]
Fixed by recent changes
