### ISSUE TITLE
Error with version 0.2.0a2

### ISSUE THREAD

**Issue by tlvu** [holoviz/jupyter-panel-proxy#21]
#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)
See inside docker image below.

Version 0.2.0a2 installed from https://anaconda.org/pyviz/jupyter-panel-proxy/files

#### Description of expected behavior and the observed behavior

Should be able to click on the Panel Launcher icon without error, got the following 2 errors instead:

```
ServerApp - ERROR - Uncaught exception GET /server-proxy/icon/panel (10.10.10.7)                                                 
HTTPServerRequest(protocol='http', host='lvu.ouranos.ca:8890', method='GET', uri='/server-proxy/icon/panel', version='HTTP/1.1', remote_ip='10.10.10.7
')                                                                                                                     
Traceback (most recent call last):                                                                               
  File "/opt/conda/envs/birdy/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute                
    result = await result                                                                                                  
  File "/opt/conda/envs/birdy/lib/python3.8/site-packages/jupyter_server_proxy/api.py", line 68, in get                
    with open(self.icons[name]) as f:                                                                                       
FileNotFoundError: [Errno 2] No such file or directory: '/opt/conda/envs/birdy/lib/python3.8/site-packages/panel_server/icons/logo.svg'


ServerApp - ERROR - Uncaught exception GET /panel/ (10.10.10.7)                                                                               
HTTPServerRequest(protocol='http', host='lvu.ouranos.ca:8890', method='GET', uri='/panel/', version='HTTP/1.1', remote_ip='10.10.10.7')               
Traceback (most recent call last):                                                                                                                    
  File "/opt/conda/envs/birdy/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute                                                     
    result = await result                                                                                                                             
  File "/opt/conda/envs/birdy/lib/python3.8/site-packages/jupyter_server_proxy/websocket.py", line 91, in get
    return await self.http_get(*args, **kwargs)
  File "/opt/conda/envs/birdy/lib/python3.8/site-packages/jupyter_server_proxy/handlers.py", line 668, in http_get
    return await ensure_async(self.proxy(self.port, path))
  File "/opt/conda/envs/birdy/lib/python3.8/site-packages/jupyter_server/utils.py", line 182, in ensure_async
    result = await obj
  File "/opt/conda/envs/birdy/lib/python3.8/site-packages/jupyter_server_proxy/handlers.py", line 662, in proxy
    await self.ensure_process()
  File "/opt/conda/envs/birdy/lib/python3.8/site-packages/jupyter_server_proxy/handlers.py", line 627, in ensure_process
    cmd = self.get_cmd()
  File "/opt/conda/envs/birdy/lib/python3.8/site-packages/jupyter_server_proxy/config.py", line 65, in get_cmd
    return self._realize_rendered_template(command)
  File "/opt/conda/envs/birdy/lib/python3.8/site-packages/jupyter_server_proxy/config.py", line 62, in _realize_rendered_template
    return self._render_template(attribute)
  File "/opt/conda/envs/birdy/lib/python3.8/site-packages/jupyter_server_proxy/config.py", line 47, in _render_template
    return [self._render_template(v) for v in value]
  File "/opt/conda/envs/birdy/lib/python3.8/site-packages/jupyter_server_proxy/config.py", line 47, in <listcomp>
    return [self._render_template(v) for v in value]
  File "/opt/conda/envs/birdy/lib/python3.8/site-packages/jupyter_server_proxy/config.py", line 45, in _render_template
    return value.format(**args)
KeyError: 'cookiecutter'
```

#### Complete, minimal, self-contained example code that reproduces the issue

* Check out repo at this specific commit https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/tree/79552ea69677f29d0ca8b647d4c2f72f8d14caff 
  * matching Binder link https://mybinder.org/v2/gh/Ouranosinc/PAVICS-e2e-workflow-tests/79552ea69677f29d0ca8b647d4c2f72f8d14caff but unable to see errors on STDOUT so have to launch the docker image locally on your machine
* Execute script `launchcontainer` from checkout to run pre-built docker image of JupyterLab with pre-installed plugins
* STDOUT will have first error `No such file or directory: '/opt/conda/envs/birdy/lib/python3.8/site-packages/panel_server/icons/logo.svg'`
* In JupyterLab, click on "Panel Launcher" icon
* STDOUT will have 2nd error `KeyError: 'cookiecutter'`

**Comment by tlvu** [comment]
@MarcSkovMadsen For your info.

**Comment by maximlt** [comment]
The first error will be fixed by https://github.com/holoviz/jupyter-panel-proxy/pull/28. Not sure about the first one.
