### ISSUE TITLE
tornado.simple_httpclient.HTTPTimeoutError: Timeout during request

### ISSUE THREAD

**Issue by scottyhq** [holoviz/jupyter-panel-proxy#7]
Hi @jsignell ! Thanks for putting this together, it nicely simplifies deployment via binder. I'm seeing an error currently related to a timeout and wondering if there is a setting to avoid this. After arriving at a 500: Internal Sever Error Page, simply reloading the page brings up the interface, so I think it is just a matter of my code taking to long to initialize? 

The jupyterhub log shows:
```
[E 2019-10-29 20:03:54.566 SingleUserNotebookApp web:1788] Uncaught exception GET /user/scottyhq/scottyhq-measures-panel-x6ryeht3/panel/measures-panel?token=zApeoBnRQgGuOCKzYhzqhQ (192.168.15.89)
    HTTPServerRequest(protocol='https', host='hub.binder.aws-useast1.pangeo.io', method='GET', uri='/user/scottyhq/scottyhq-measures-panel-x6ryeht3/panel/measures-panel?token=zApeoBnRQgGuOCKzYhzqhQ', version='HTTP/1.1', remote_ip='192.168.15.89')
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyter_server_proxy/websocket.py", line 94, in get
        return await self.http_get(*args, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyter_server_proxy/handlers.py", line 438, in http_get
        return await self.proxy(self.port, path)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyter_server_proxy/handlers.py", line 434, in proxy
        return await super().proxy(self.port, path)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyter_server_proxy/handlers.py", line 199, in proxy
        response = await client.fetch(req, raise_error=False)
    tornado.simple_httpclient.HTTPTimeoutError: Timeout during request
```

Here is a link if you need to investigate:
https://binder.aws-useast1.pangeo.io/v2/gh/scottyhq/measures-panel/panel-proxy?urlpath=panel/measures-panel

<details><summary>And a list of package versions</summary>
<p>

 packages in environment at /srv/conda/envs/notebook:
```
Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
affine                    2.3.0                      py_0    conda-forge
aiohttp                   3.6.1            py37h516909a_0    conda-forge
alembic                   1.1.0                      py_0    conda-forge
asn1crypto                0.24.0                py37_1003    conda-forge
async-timeout             3.0.1                   py_1000    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     19.1.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bleach                    3.1.0                      py_0    conda-forge
blinker                   1.4                        py_1    conda-forge
bokeh                     1.3.4                    py37_0    conda-forge
boost-cpp                 1.70.0               h8e57a91_2    conda-forge
boto3                     1.9.253                    py_0    conda-forge
botocore                  1.12.253                   py_0    conda-forge
bzip2                     1.0.8                h516909a_1    conda-forge
ca-certificates           2019.9.11            hecc5488_0    conda-forge
cairo                     1.16.0            hfb77d84_1002    conda-forge
certifi                   2019.9.11                py37_0    conda-forge
certipy                   0.1.3                      py_0    conda-forge
cffi                      1.12.3           py37h8022711_0    conda-forge
cfitsio                   3.470                hb60a0a2_2    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
cloudpickle               1.2.2                      py_0    conda-forge
colorcet                  2.0.1                      py_0    conda-forge
configurable-http-proxy   1.3.0                         0    conda-forge
cryptography              2.7              py37h72c5cf5_0    conda-forge
curl                      7.65.3               hf8cf82a_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cytoolz                   0.10.0           py37h516909a_0    conda-forge
dask                      2.6.0                      py_0    conda-forge
dask-core                 2.6.0                      py_0    conda-forge
datashader                0.8.0                      py_0    conda-forge
datashape                 0.5.4                      py_1    conda-forge
decorator                 4.4.0                      py_0    conda-forge
defusedxml                0.5.0                      py_1    conda-forge
distributed               2.6.0                      py_0    conda-forge
docutils                  0.15.2                   py37_0    conda-forge
entrypoints               0.3                   py37_1000    conda-forge
expat                     2.2.5             he1b5a44_1004    conda-forge
fiona                     1.8.9.post2      py37hdff7cfa_0    conda-forge
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
freexl                    1.0.5             h14c3975_1002    conda-forge
fsspec                    0.5.2                      py_0    conda-forge
gdal                      2.4.2            py37h5f563d9_4    conda-forge
geopandas                 0.6.1                      py_1    conda-forge
geos                      3.7.2                he1b5a44_2    conda-forge
geotiff                   1.5.1                h560c3f3_2    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
giflib                    5.1.7                h516909a_1    conda-forge
glib                      2.58.3            h6f030ca_1002    conda-forge
hdf4                      4.2.13            h9a582f1_1002    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1104    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
holoviews                 1.12.6                     py_0    conda-forge
hvplot                    0.5.2                      py_0    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.8                   py37_1000    conda-forge
imageio                   2.6.1                    py37_0    conda-forge
ipykernel                 5.1.2            py37h5ca1d4c_0    conda-forge
ipython                   7.8.0            py37h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.4.2                      py_0    conda-forge
jedi                      0.15.1                   py37_0    conda-forge
jinja2                    2.10.1                     py_0    conda-forge
jmespath                  0.9.4                      py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
json-c                    0.13.1            h14c3975_1001    conda-forge
json5                     0.8.5                      py_0    conda-forge
jsonschema                3.0.2                    py37_0    conda-forge
jupyter-panel-proxy       0.1.0                    pypi_0    pypi
jupyter-server-proxy      1.1.0                      py_0    conda-forge
jupyter_client            5.3.1                      py_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyterhub                1.0.0                    py37_0    conda-forge
jupyterlab                1.1.4                      py_0    conda-forge
jupyterlab_server         1.0.6                      py_0    conda-forge
kealib                    1.4.10            h58c409b_1005    conda-forge
kiwisolver                1.1.0            py37hc9558a2_0    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libcurl                   7.65.3               hda55be3_0    conda-forge
libdap4                   3.20.4               hd3bb157_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libgdal                   2.4.2                hbef8c27_4    conda-forge
libgfortran-ng            7.3.0                hdf63c60_2    conda-forge
libiconv                  1.15              h516909a_1005    conda-forge
libkml                    1.3.0             h4fcabce_1010    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libllvm8                  8.0.1                hc9558a2_0    conda-forge
libnetcdf                 4.6.2             h303dfb8_1003    conda-forge
libopenblas               0.3.7                h6e990d7_2    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libpq                     11.5                 hd9ab2ff_1    conda-forge
libsodium                 1.0.17               h516909a_0    conda-forge
libspatialindex           1.9.3                he1b5a44_0    conda-forge
libspatialite             4.3.0a            he1bb1e1_1029    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
libtiff                   4.0.10            hfc65ed5_1004    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libuv                     1.32.0               h516909a_0    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.9                hee79883_5    conda-forge
llvmlite                  0.30.0           py37h8b12597_0    conda-forge
locket                    0.2.0                      py_2    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
mako                      1.1.0                      py_0    conda-forge
markdown                  3.1.1                      py_0    conda-forge
markupsafe                1.1.1            py37h14c3975_0    conda-forge
matplotlib-base           3.1.1            py37he7580a8_1    conda-forge
mistune                   0.8.4           py37h14c3975_1000    conda-forge
msgpack-python            0.6.2            py37hc9558a2_0    conda-forge
multidict                 4.5.2           py37h14c3975_1000    conda-forge
multipledispatch          0.6.0                      py_0    conda-forge
munch                     2.3.2                      py_0    conda-forge
nbconvert                 5.4.1                      py_2    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
networkx                  2.4                        py_0    conda-forge
nodejs                    12.11.1              h10a4023_0    conda-forge
notebook                  5.7.8                    py37_1    conda-forge
nteract_on_jupyter        2.1.3                      py_0    conda-forge
numba                     0.46.0           py37hb3f55d8_0    conda-forge
numpy                     1.17.3           py37h95a1406_0    conda-forge
oauthlib                  3.0.1                      py_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openjpeg                  2.3.1                h21c5421_1    conda-forge
openssl                   1.1.1c               h516909a_0    conda-forge
packaging                 19.2                       py_0    conda-forge
pamela                    1.0.0                      py_0    conda-forge
pandas                    0.25.2           py37hb3f55d8_0    conda-forge
pandoc                    2.7.3                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
panel                     0.6.4                         0    conda-forge
param                     1.9.2                      py_0    conda-forge
parso                     0.5.1                      py_0    conda-forge
partd                     1.0.0                      py_0    conda-forge
pcre                      8.43                 he1b5a44_0    conda-forge
pexpect                   4.7.0                    py37_0    conda-forge
pickleshare               0.7.5                 py37_1000    conda-forge
pillow                    6.2.1            py37h6b7be26_0    conda-forge
pip                       19.3.1                   py37_0    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
poppler                   0.67.0               ha967d66_7    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                11.5                 hc63931a_1    conda-forge
proj4                     6.1.0                he751ad9_2    conda-forge
prometheus_client         0.7.1                      py_0    conda-forge
prompt_toolkit            2.0.9                      py_0    conda-forge
psutil                    5.6.3            py37h516909a_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pyct                      0.4.6                      py_0    conda-forge
pyct-core                 0.4.6                      py_0    conda-forge
pycurl                    7.43.0.2         py37h16ce93b_1    conda-forge
pygments                  2.4.2                      py_0    conda-forge
pyjwt                     1.7.1                      py_0    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
pyparsing                 2.4.2                      py_0    conda-forge
pyproj                    2.2.1            py37hc44880f_0    conda-forge
pyrsistent                0.15.4           py37h516909a_0    conda-forge
pysocks                   1.7.0                    py37_0    conda-forge
python                    3.7.3                h33d41f4_1    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
python-editor             1.0.4                      py_0    conda-forge
pytz                      2019.3                     py_0    conda-forge
pyviz_comms               0.7.2                      py_0    conda-forge
pywavelets                1.1.1            py37hc1659b7_0    conda-forge
pyyaml                    5.1.2            py37h516909a_0    conda-forge
pyzmq                     18.1.0           py37h1768529_0    conda-forge
rasterio                  1.0.28           py37hdff7cfa_1    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.22.0                   py37_1    conda-forge
rtree                     0.8.3           py37h666c49c_1002    conda-forge
s3transfer                0.2.1                    py37_0    conda-forge
scikit-image              0.16.2           py37hb3f55d8_0    conda-forge
scipy                     1.3.1            py37h921218d_2    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                41.2.0                   py37_0    conda-forge
shapely                   1.6.4           py37hec07ddf_1006    conda-forge
simpervisor               0.3                        py_1    conda-forge
six                       1.12.0                py37_1000    conda-forge
snuggs                    1.4.7                      py_0    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
sqlalchemy                1.3.8            py37h516909a_0    conda-forge
sqlite                    3.29.0               hcee41ef_1    conda-forge
tblib                     1.4.0                      py_0    conda-forge
terminado                 0.8.2                    py37_0    conda-forge
testpath                  0.4.2                   py_1001    conda-forge
tk                        8.6.9             hed695b0_1003    conda-forge
toolz                     0.10.0                     py_0    conda-forge
tornado                   6.0.3            py37h516909a_0    conda-forge
traitlets                 4.3.2                 py37_1000    conda-forge
tzcode                    2019a             h516909a_1002    conda-forge
urllib3                   1.25.3                   py37_0    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.33.6                   py37_0    conda-forge
widgetsnbextension        3.4.2                 py37_1000    conda-forge
xarray                    0.14.0                     py_0    conda-forge
xerces-c                  3.2.2             h8412b87_1004    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.9                h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.1.7             h14c3975_1001    conda-forge
yarl                      1.3.0           py37h14c3975_1000    conda-forge
zeromq                    4.3.2                he1b5a44_2    conda-forge
zict                      1.0.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.3                h3b9ef0a_0    conda-forge
```
</p>
</details>

**Comment by jsignell** [comment]
I'm not sure how to debug that. I see the same behavior. Maybe @philippjfr has an idea?

**Comment by maximlt** [comment]
Hi!
Not sure it's the best place to report this but I've got a similar issue trying to run the [nyc_taxi app](https://github.com/pyviz-demos/nyc_taxi) -> I've got a blank page with a "Timeout during request" message and that's it. I've got the same issue trying to open an app I've just built. I don't know how to get the logs thought to provide you with some more info :/

**Comment by rsignell-usgs** [comment]
@scottyhq , I just tried hitting the URL: https://aws-uswest2-binder.pangeo.io/v2/gh/scottyhq/measures-panel/panel-proxy?urlpath=panel/measures-panel
and the app came right up without the timeout message:
![2020-03-04_8-44-27](https://user-images.githubusercontent.com/1872600/75885381-69674380-5df4-11ea-902a-704b9acd6fa5.png)

The only thing that should have changed was the binder deployment itself, right?

**Comment by oeway** [comment]
I think it's because the default request timeout for tornado web is 20s, while the browser typically have much longer request timeout. See here: https://github.com/jupyterhub/jupyter-server-proxy/issues/182

I will try to make PR for this to the jupyter server proxy repo.

**Comment by jsignell** [comment]
Thanks @oeway!

**Comment by maximlt** [comment]
This seems to have been fixed a while back in jupyter-proxy-server with https://github.com/jupyterhub/jupyter-server-proxy/pull/183.
